FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt
RUN python -m pip install requests

COPY data_output /data_output
COPY config.ini /data_output/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /data_output
USER appuser

WORKDIR /data_output
CMD ["python", "data_output.py", "config.ini"]

EXPOSE 5007
