FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY data_input /data_input
COPY config.ini /data_input/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /data_input
USER appuser

WORKDIR /data_input
CMD ["python", "data_input.py", "config.ini"]

EXPOSE 5002
