FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY sensor_value_handler /sensor_value_handler
COPY config.ini /sensor_value_handler/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /sensor_value_handler
USER appuser

WORKDIR /sensor_value_handler
CMD ["python", "sensor_value_handler.py", "config.ini"]

EXPOSE 5004
