FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY system /system
COPY config.ini /system/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /system
USER appuser

WORKDIR /system
CMD ["python", "system.py", "config.ini"]

EXPOSE 5005
