### Отработка сценария тревоги
POST http://localhost:5002/ingest HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "url": "http://sensor_value_handler:5006",
    "value": 15,
    "in_source": {"Security": "connect", "Technical": "connect"},
    "target": "sensor_value_handler",
    "digest": "G1I9Qoi_W7OBrbMwH7TESx3zUo47G-ruw3",
    "operation": "check_alarm",
    "digest_alg": "sha256"
}

### Отработка сценария вставки ключей
POST http://localhost:5002/ingest HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "url": "http://sensor_value_handler:5006",
    "value": 15,
    "in_source": {"Security": "connect", "Technical": "connect"},
    "target": "monitor",
    "digest": "G1I9Qoi_W7OBrbMwH7TESx3zUo47G-ruw3",
    "operation": "insert_key",
    "digest_alg": "sha256"
}

### Отработка сценария смены значения тревоги
POST http://localhost:5002/ingest HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "url": "http://sensor_value_handler:5006",
    "value": 15,
    "in_source": {"Security": "connect", "Technical": "connect"},
    "target": "sensor_value_handler",
    "digest": "G1I9Qoi_W7OBrbMwH7TESx3zUo47G-ruw3",
    "operation": "update_coef",
    "digest_alg": "sha256"
}

### Отработка сценария вынимание ключей
POST http://localhost:5002/ingest HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "url": "http://sensor_value_handler:5006",
    "value": 15,
    "in_source": {"Security": "connect", "Technical": "connect"},
    "target": "monitor",
    "digest": "G1I9Qoi_W7OBrbMwH7TESx3zUo47G-ruw3",
    "operation": "pulled_out_key",
    "digest_alg": "sha256"
}

### Отработка сценария обновления системы
POST http://localhost:5002/ingest HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "url": "http://file_server:6001",
    "value": 15,
    "in_source": {"Security": "connect", "Technical": "connect"},
    "target": "system",
    "digest": "G1I9Qoi_W7OBrbMwH7TESx3zUo47G-ruw3",
    "operation": "update_system",
    "digest_alg": "sha256"
}